// Link's puzzles: [first, link, second]. The link finishes the first word and starts the
// second: SUN + LIGHT = sunlight, LIGHT + HOUSE = lighthouse. Add freely; each day's five are
// drawn from this list by date, so editing it changes which ones fall on which day.
export const LINKS = `
  sun light house
  fire place mat
  rain bow tie
  snow ball room
  book mark down
  foot ball park
  door bell boy
  tooth paste board
  water fall out
  hand shake down
  back pack horse
  day dream boat
  night club house
  star fish bowl
  sea side walk
  head line up
  break fast food
  air port hole
  black board game
  card board walk
  blue bird bath
  butter fly paper
  cross word play
  eye brow beat
  farm house boat
  green house plant
  high way side
  home work shop
  key board room
  life time table
  lime light year
  moon light bulb
  news paper clip
  over time zone
  pan cake walk
  play ground floor
  post card game
  rail road map
  sand box car
  school bus stop
  ship yard stick
  show case study
  sky line dance
  soft ware house
  sun flower pot
  table top hat
  tea pot hole
  thunder storm cloud
  under ground hog
  wall paper weight
  week end game
  wind mill stone
  wood work out
  cup cake stand
  drive way point
  ear ring leader
  ice cream cheese
  jelly fish tank
  pine apple sauce
  pop corn bread
  sea shell fish
  honey moon walk
  down town hall
  fire work force
  gold fish hook
  horse back yard
  hot dog house
  note book shop
  out door mat
  pass word search
  race horse shoe
  spot light house
  tool box office
  touch down pour
  water melon ball
  bed room mate
  boat house keeper
  class room service
  copy cat walk
  dead line up
  finger nail polish
  grand father figure
  hair brush stroke
  hall way out
  heart beat box
  left over night
  long shot gun
`.trim().split("\n").map((line) => line.trim().split(" "));
