// The list of games shown on the hub. Adding a game = add a folder under web/games/
// and one entry here (and, if it uses the API, one module in api/src/games/).
// `status`: "live" can be played; "soon" shows a dimmed teaser card.
// `accent`: the game's own color. Every game gets a different one.
// `category`: the act the game belongs to ("Play" or "Know"), in the order of CATEGORIES.
// The order of the games within an act is set in series.js. "Finale" is Risk (in the house/ folder), which
// is reached from the Series rather than listed with the episodes.
export const CATEGORIES = ["Play", "Know"];

export const GAMES = [
  {
    id: "orbit",
    name: "Orbit",
    tagline: "Tap to sling a ship from planet to planet.",
    category: "Play",
    accent: "#A78BFA",
    path: "games/orbit/",
    launchDay: "2026-10-05",
    maxScore: 5,
    status: "live",
  },
  {
    id: "pins",
    name: "Pins",
    tagline: "Three frames of bowling, two taps a ball.",
    category: "Play",
    accent: "#F27DB0",
    path: "games/pins/",
    launchDay: "2026-10-05",
    maxScore: 90,
    status: "live",
  },
  {
    id: "skip",
    name: "Skip",
    tagline: "Skip a stone. Tap every time it touches the water.",
    category: "Play",
    accent: "#5BB8F5",
    path: "games/skip/",
    launchDay: "2026-10-05",
    maxScore: 30,
    status: "live",
  },
  {
    id: "hole",
    name: "Hole",
    tagline: "One golf hole a day. Aim, then power.",
    category: "Play",
    accent: "#6FDC8C",
    path: "games/hole/",
    launchDay: "2026-10-05",
    maxScore: 8,
    status: "live",
  },
  {
    id: "stop",
    name: "Stop",
    tagline: "Stop the needle on the mark. Five rounds, each faster.",
    category: "Play",
    accent: "#F47A6B",
    path: "games/stop/",
    launchDay: "2026-10-05",
    maxScore: 100,
    status: "live",
  },
  {
    id: "middleman",
    name: "Middleman",
    tagline: "Name the thing halfway between two others.",
    category: "Know",
    accent: "#F59E4C",
    path: "games/middleman/",
    launchDay: "2026-10-05",
    maxScore: 500,
    status: "live",
  },
  {
    id: "year",
    name: "Year",
    tagline: "What year was it invented or built?",
    category: "Know",
    accent: "#B7E05A",
    path: "games/year/",
    launchDay: "2026-10-05",
    maxScore: 100,
    status: "live",
  },
  {
    id: "close",
    name: "Close",
    tagline: "How heavy, how fast, how big, how much? Get close.",
    category: "Know",
    accent: "#D46BE8",
    path: "games/close/",
    launchDay: "2026-10-05",
    maxScore: 100,
    status: "live",
  },
  {
    id: "jot",
    name: "Jot",
    tagline: "Find the hidden word from letter counts alone.",
    category: "Know",
    accent: "#E2C7A0",
    path: "games/jot/",
    launchDay: "2026-10-05",
    maxScore: 100,
    status: "live",
  },
  {
    id: "link",
    name: "Link",
    tagline: "One word finishes the first and starts the second.",
    category: "Know",
    accent: "#F5D547",
    path: "games/link/",
    launchDay: "2026-10-05",
    maxScore: 100,
    status: "live",
  },
  {
    id: "house",
    name: "Risk",
    tagline: "Risk your day's points at the casino tables.",
    category: "Finale",
    accent: "#2DD4BF",
    path: "games/house/",
    launchDay: "2026-10-05",
    maxScore: 1000,
    status: "live",
  },
];
