// Regenerates web/games/orbit/core/levels.js: the list of seeds that make fair Orbit levels.
// Run `npm run orbit:levels` after changing anything in core/sim.js or core/solver.js, because
// a physics change can turn a fair level into an impossible one.
//
// Like a catalog edit in Middleman, rewriting this list changes the puzzle for every date,
// so deploy it right after midnight.
import { writeFileSync } from "node:fs";
import { makeLevel } from "../web/games/orbit/core/sim.js";
import { rate } from "../web/games/orbit/core/solver.js";

const COUNT = Number(process.argv[2]) || 730; // two years of daily puzzles
const OUT = new URL("../web/games/orbit/core/levels.js", import.meta.url);

const seeds = [];
const pars = {};
let seed = 0;
while (seeds.length < COUNT) {
  seed++;
  const rating = rate(makeLevel(seed));
  if (!rating) continue;
  seeds.push(seed);
  pars[rating.par] = (pars[rating.par] ?? 0) + 1;
}

const rows = [];
for (let i = 0; i < seeds.length; i += 16) rows.push("  " + seeds.slice(i, i + 16).join(", ") + ",");
writeFileSync(OUT, `// Generated by tools/orbit-levels.js (npm run orbit:levels). Do not edit by hand.
// Each number is a seed for makeLevel() that the solver has checked: winnable in 3 or 4 jumps
// through generous launch windows. One seed per day, in order, starting on Orbit's launch day.
export const SEEDS = [
${rows.join("\n")}
];
`);
console.log(`Wrote ${seeds.length} seeds (tried ${seed}). Jumps needed with generous windows:`, pars);
