// Regenerates web/games/pegs/core/levels.js: the list of seeds that make fair Pegs fields.
// Run `npm run pegs:levels` after changing anything in core/sim.js or core/solver.js, because
// a physics change can turn a clearable field into an impossible one.
//
// Rewriting this list changes the puzzle for every date, so deploy it right after midnight.
import { writeFileSync } from "node:fs";
import { makeField } from "../web/games/pegs/core/sim.js";
import { isFair } from "../web/games/pegs/core/solver.js";

const COUNT = Number(process.argv[2]) || 730; // two years of daily puzzles
const OUT = new URL("../web/games/pegs/core/levels.js", import.meta.url);

const seeds = [];
let seed = 0;
while (seeds.length < COUNT) {
  seed++;
  if (isFair(makeField(seed))) seeds.push(seed);
}

const rows = [];
for (let i = 0; i < seeds.length; i += 16) rows.push("  " + seeds.slice(i, i + 16).join(", ") + ",");
writeFileSync(OUT, `// Generated by tools/pegs-levels.js (npm run pegs:levels). Do not edit by hand.
// Each number is a seed for makeField() that the solver has checked: every accent peg can be
// cleared with four balls. One seed per day, in order, starting on Pegs' launch day.
export const SEEDS = [
${rows.join("\n")}
];
`);
console.log(`Wrote ${seeds.length} seeds (tried ${seed}).`);
